#!/usr/bin/env bash
# ============================================================================
# Section 10 — Generate validation script at ~/.local/bin/zenbook-validate
#
# A standalone script the user can re-run anytime to verify the install state.
# Always generated (called via trap in setup.sh, even on early exit).
# ============================================================================

# shellcheck source=common.sh
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

run_section_10_validate() {
    log "=== Section 10: Validation script generation ==="

    local target="$HOME/.local/bin/zenbook-validate"
    ensure_dir "$(dirname "$target")"

    if [[ "$DRY_RUN" == "true" ]]; then
        log "[DRY-RUN] would generate $target"
        return 0
    fi

    cat > "$target" <<'VALIDATE_EOF'
#!/usr/bin/env bash
# zenbook-validate — verify the state of a zenbook-s16-ubuntu-setup install.
# Generated by https://github.com/MixedDrive-Lab/zenbook-s16-ubuntu-setup

set -u

ok()    { printf '  \033[0;32m✓\033[0m %s\n' "$1"; }
miss()  { printf '  \033[0;31m✗\033[0m %s\n' "$1"; }
hdr()   { printf '\n\033[1m%s\033[0m\n' "$1"; }

cmd_check() {
    local name="$1"; local cmd="$2"
    if command -v "$cmd" &>/dev/null; then ok "$name"; else miss "$name"; fi
}

flatpak_check() {
    local app_id="$1"
    # Use --columns=application to get just the App ID column reliably,
    # regardless of locale, flatpak version, or app name word count.
    if flatpak list --app --columns=application 2>/dev/null | grep -qx "$app_id"; then
        ok "$app_id"
    else
        miss "$app_id"
    fi
}

echo "=== zenbook-validate — $(date) ==="

hdr "OS / Kernel"
echo "  $(lsb_release -ds 2>/dev/null || echo '(lsb_release missing)')"
echo "  Kernel: $(uname -r)"
echo "  Architecture: $(uname -m)"
echo "  Display: ${XDG_SESSION_TYPE:-unknown}"

hdr "amdxdna NPU (multi-method)"
# Known AMD Ryzen AI NPU PCI device IDs (vendor 1022 = AMD):
#   1022:17f0  Strix Point / Krackan Point / Strix Halo (XDNA 2)
#   1022:17f1  Strix Halo (newer rev — not yet validated)
#   1022:1502  Phoenix (XDNA 1, older Ryzen 7040)
#   1022:150e  Hawk Point (XDNA 1.5)
# Source: https://github.com/skitzo2000/nix-xdna#hardware-support
if lspci -nn 2>/dev/null | grep -iqE "1022:(17f0|17f1|1502|150e)"; then
    npu_id=$(lspci -nn 2>/dev/null | grep -ioE "1022:(17f0|17f1|1502|150e)" | head -1)
    ok "lspci: AMD NPU detected ($npu_id)"
elif lspci -nn 2>/dev/null | grep -iq "signal processing"; then
    sig_dev=$(lspci -nn 2>/dev/null | grep -i "signal processing" | head -1 | grep -oE "1022:[0-9a-f]+" || echo "(unknown ID)")
    ok "lspci: Signal processing controller detected ($sig_dev) — NPU likely, verify ID"
else
    miss "lspci: no AMD NPU detected (expected 1022:17f0 for Strix Point)"
fi
if lsmod 2>/dev/null | grep -q amdxdna; then
    ok "lsmod: amdxdna module loaded"
else
    miss "lsmod: amdxdna module not loaded"
fi
if [[ -d /dev/accel ]] && [[ -n "$(ls -A /dev/accel 2>/dev/null)" ]]; then
    ok "/dev/accel populated"
else
    miss "/dev/accel missing or empty"
fi
if sudo -n dmesg 2>/dev/null | grep -qiE "amdxdna|xdna"; then
    ok "dmesg: amdxdna entries present"
else
    miss "dmesg: no amdxdna entries (try: sudo dmesg | grep -i amdxdna)"
fi

hdr "GPU / Vulkan"
lspci 2>/dev/null | grep -iE "vga|3d|display" | sed 's/^/  /' || true
if command -v vulkaninfo &>/dev/null; then
    if vulkaninfo --summary 2>/dev/null | grep -qE "Radeon|amdgpu"; then
        ok "Vulkan: AMD GPU detected"
    else
        miss "Vulkan: no AMD GPU in summary"
    fi
else
    miss "vulkaninfo not installed"
fi

hdr "Build tools"
cmd_check "gcc"     gcc
cmd_check "g++"     g++
cmd_check "cmake"   cmake
cmd_check "make"    make
cmd_check "git"     git
cmd_check "pkg-config" pkg-config

hdr "Languages (mise-managed; system-level fallback shown)"
cmd_check "python3" python3
cmd_check "node"    node
cmd_check "npm"     npm
cmd_check "rustc"   rustc
cmd_check "cargo"   cargo
cmd_check "go"      go
cmd_check "java"    java
cmd_check "ruby"    ruby
cmd_check "php"     php
cmd_check "elixir"  elixir
cmd_check "erl (Erlang)" erl
cmd_check "gfortran" gfortran
cmd_check "mise"    mise
cmd_check "rustup"  rustup
cmd_check "composer" composer
cmd_check "rails"   rails
cmd_check "uv (Astral)" uv

hdr "mise default languages (--with-mise-defaults)"
if command -v mise &>/dev/null; then
    mise_pinned=$(mise ls --installed 2>/dev/null || mise ls 2>/dev/null || true)
    if [[ -n "$mise_pinned" ]]; then
        for lang in node python go java ruby erlang elixir; do
            if echo "$mise_pinned" | grep -qE "^$lang\b"; then
                ok "mise has $lang installed"
            else
                miss "mise does NOT have $lang installed"
            fi
        done
    else
        miss "mise installed but no tools — run --with-mise-defaults"
    fi
else
    miss "mise not installed — run Section 05"
fi

hdr "Container"
cmd_check "docker"        docker
if command -v docker &>/dev/null; then
    docker compose version &>/dev/null && ok "docker compose v2 plugin" || miss "docker compose v2 plugin"
fi

hdr "AI stack (--with-ai-stack)"
cmd_check "cursor"           cursor
cmd_check "warp-terminal" warp-terminal
cmd_check "claude (Claude Code CLI)" claude

hdr "Apps stack (--with-apps)"
cmd_check "1password"  1password
cmd_check "google-chrome" google-chrome
dpkg -l localsend 2>/dev/null | grep -q "^ii" && ok "localsend" || miss "localsend"
cmd_check "typora"     typora
cmd_check "gum"        gum
cmd_check "lazygit"    lazygit
cmd_check "lazydocker" lazydocker
cmd_check "ulauncher"  ulauncher
cmd_check "fastfetch"  fastfetch

hdr "Flatpak apps (--with-flatpak)"
if command -v flatpak &>/dev/null; then
    for id in \
        org.onlyoffice.desktopeditors \
        md.obsidian.Obsidian \
        org.audacityteam.Audacity \
        org.gimp.GIMP \
        com.github.PintaProject.Pinta \
        org.videolan.VLC \
        fr.handbrake.ghb \
        org.kde.kdenlive \
        com.spotify.Client \
        com.discordapp.Discord \
        us.zoom.Zoom
    do
        flatpak_check "$id"
    done
else
    miss "flatpak not installed"
fi

hdr "Gaming (--with-gaming)"
cmd_check "steam" steam
if dpkg --print-foreign-architectures 2>/dev/null | grep -qx i386; then
    ok "i386 architecture enabled (Steam-ready)"
else
    miss "i386 architecture NOT enabled (Steam will fail to install — run: sudo dpkg --add-architecture i386 && sudo apt update)"
fi

hdr "XRT NPU stack (--with-xrt)"
if [[ -x /opt/xilinx/xrt/bin/xrt-smi ]]; then
    ok "xrt-smi installed at /opt/xilinx/xrt/bin/xrt-smi"
    # Quick examine — exit code typically 0 even if no NPU; parse output
    xrt_out=$(sudo -n /opt/xilinx/xrt/bin/xrt-smi examine 2>&1 || true)
    if echo "$xrt_out" | grep -qiE "NPU|Strix|amdxdna"; then
        ok "xrt-smi examine reports NPU device"
    else
        miss "xrt-smi examine ran but did not report an NPU device"
    fi
else
    miss "xrt-smi not installed (run --with-xrt; see docs/09-xrt-stack.md)"
fi
if dpkg -l rocm-core 2>/dev/null | grep -q "^ii"; then
    ok "rocm-core installed (ROCm runtime present)"
else
    miss "rocm-core not installed"
fi
if id -nG 2>/dev/null | grep -qw render; then
    ok "$USER in 'render' group"
else
    miss "$USER NOT in 'render' group (XRT won't see NPU)"
fi
if id -nG 2>/dev/null | grep -qw video; then
    ok "$USER in 'video' group"
else
    miss "$USER NOT in 'video' group"
fi
if [[ -f /etc/security/limits.d/99-amdxdna.conf ]]; then
    ok "memlock limits configured at /etc/security/limits.d/99-amdxdna.conf"
else
    miss "memlock limits not configured (large NPU buffers may fail)"
fi

hdr "Kernel hold status"
if apt-mark showhold 2>/dev/null | grep -q "^linux-image-generic"; then
    ok "linux-image-generic is held (good — won't auto-upgrade past 6.17.0-20)"
else
    miss "linux-image-generic NOT held — apt-get upgrade may break amdxdna"
fi
# Cross-check that we're actually booted on the held kernel
if [[ "$(uname -r)" == "6.17.0-20-generic" ]]; then
    ok "Currently booted on 6.17.0-20-generic"
else
    miss "Booted on $(uname -r) — expected 6.17.0-20-generic. Reboot and pick the right kernel."
fi
# GRUB default — accept multiple valid formats
if [[ -f /etc/default/grub ]]; then
    grub_default=$(grep '^GRUB_DEFAULT=' /etc/default/grub 2>/dev/null | head -1)
    if [[ -z "$grub_default" ]]; then
        miss "GRUB_DEFAULT not set in /etc/default/grub"
    elif echo "$grub_default" | grep -qE '6\.17\.0-20|gnulinux-6\.17\.0-20'; then
        ok "GRUB_DEFAULT points to 6.17.0-20: $grub_default"
    elif echo "$grub_default" | grep -qE 'GRUB_DEFAULT="[0-9]+>[0-9]+"'; then
        # Position-based — verify by booted kernel; if -20 booted, it's working
        if [[ "$(uname -r)" == "6.17.0-20-generic" ]]; then
            ok "GRUB_DEFAULT uses position fallback ($grub_default) — working (booted -20)"
        else
            miss "GRUB_DEFAULT=$grub_default but booted $(uname -r) — fallback not pointing to -20"
        fi
    elif echo "$grub_default" | grep -q '^GRUB_DEFAULT=saved'; then
        miss "GRUB_DEFAULT=saved relies on grubenv (fragile). Setup script v0.1.2+ uses static value instead."
    else
        miss "GRUB_DEFAULT is unrecognized: $grub_default"
    fi
fi

hdr "Storage"
df -h | grep -E "^/dev/" | head -5 | sed 's/^/  /'

echo ""
echo "=== Validation complete ==="
VALIDATE_EOF

    chmod +x "$target"
    success "Validation script generated at $target"
    log "Run anytime with: zenbook-validate"
}
